"""Verify the TOI catalog schema against the live archive (D-013).

Nothing in this script assumes a column name. It asks the archive what columns
exist, what dispositions are actually used, and how many rows carry each, then
writes a dated snapshot to docs/.

Run this before writing any catalog code:

    python scripts/00_verify_toi_schema.py

The snapshot is committed. Later decisions cite it, so a schema change is
visible as a diff rather than as a silently broken query.
"""

from __future__ import annotations

import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

import pyvo

TAP_URL = "https://exoplanetarchive.ipac.caltech.edu/TAP"
TABLE = "toi"
REFERENCE_TIC = 261136679          # Pi Mensae, D-007
OUT = Path(__file__).resolve().parents[1] / "docs" / "toi-schema-snapshot.md"


def query(service: pyvo.dal.TAPService, adql: str):
    return service.search(adql).to_table()


def discover_columns(service) -> list[tuple[str, str, str]]:
    """Ask the archive which columns the TOI table has. No assumptions."""
    rows = query(service, f"""
        SELECT column_name, datatype, description
        FROM TAP_SCHEMA.columns
        WHERE table_name = '{TABLE}'
        ORDER BY column_name
    """)
    out = []
    for r in rows:
        out.append((
            str(r["column_name"]),
            str(r.get("datatype", "")),
            str(r.get("description", "") or "").strip(),
        ))
    return out


def find_disposition_columns(columns) -> list[str]:
    """Locate disposition columns by name or description, rather than guessing."""
    found = []
    for name, _dtype, desc in columns:
        haystack = f"{name} {desc}".lower()
        if "disp" in haystack:
            found.append(name)
    return found


def distribution(service, column: str) -> Counter:
    rows = query(service, f"""
        SELECT {column}, COUNT(*) AS n
        FROM {TABLE}
        GROUP BY {column}
    """)
    counts = Counter()
    for r in rows:
        key = r[column]
        key = "(null)" if key is None or str(key).strip() == "" else str(key).strip()
        counts[key] = int(r["n"])
    return counts


def reference_row(service, columns):
    """Pull the reference target, to see a real populated row."""
    tic_col = next((n for n, _, d in columns
                    if n.lower() in {"tid", "tic_id"} or "tic" in d.lower()), None)
    if tic_col is None:
        return None, None
    rows = query(service, f"SELECT * FROM {TABLE} WHERE {tic_col} = {REFERENCE_TIC}")
    return tic_col, rows


def main() -> None:
    print(f"connecting to {TAP_URL} ...")
    service = pyvo.dal.TAPService(TAP_URL)

    try:
        columns = discover_columns(service)
    except Exception as exc:  # noqa: BLE001 - a diagnostic script reports, it does not recover
        sys.exit(f"schema query failed: {exc}")

    print(f"{len(columns)} columns in table '{TABLE}'")

    disp_cols = find_disposition_columns(columns)
    print(f"disposition-like columns: {disp_cols or 'NONE FOUND - investigate'}")

    distributions = {}
    for col in disp_cols:
        try:
            distributions[col] = distribution(service, col)
            print(f"  {col}: {len(distributions[col])} distinct values")
        except Exception as exc:  # noqa: BLE001 - one failing column must not stop the rest
            print(f"  {col}: query failed ({exc})")

    tic_col, ref = reference_row(service, columns)
    if ref is not None and len(ref):
        print(f"reference target found via '{tic_col}': {len(ref)} row(s)")
    else:
        print("reference target NOT found - check the TIC column name")

    # --- snapshot -----------------------------------------------------------
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# TOI catalog schema snapshot",
        "",
        "Generated by `scripts/00_verify_toi_schema.py`. Do not edit by hand.",
        "",
        f"- Retrieved: {stamp}",
        f"- Service: {TAP_URL}",
        f"- Table: `{TABLE}`",
        f"- Columns: {len(columns)}",
        "",
        "## Disposition columns",
        "",
    ]

    if not disp_cols:
        lines += ["None found by name or description. Investigate before", 
                  "implementing D-013.", ""]

    for col, counts in distributions.items():
        total = sum(counts.values())
        lines += [f"### `{col}`", "", f"{total} rows.", "",
                  "| value | count | share |", "|---|---:|---:|"]
        for value, n in counts.most_common():
            lines.append(f"| `{value}` | {n} | {n / total:.1%} |")
        lines.append("")

    if ref is not None and len(ref):
        lines += ["## Reference target",
                  "",
                  f"TIC {REFERENCE_TIC} (Pi Mensae), matched on `{tic_col}`.",
                  "Populated columns only:",
                  "",
                  "| column | value |", "|---|---|"]
        row = ref[0]
        for name in ref.colnames:
            value = row[name]
            if value is None or str(value).strip() in {"", "--", "nan"}:
                continue
            lines.append(f"| `{name}` | {value} |")
        lines.append("")

    lines += ["## All columns", "", "| column | type | description |", "|---|---|---|"]
    for name, dtype, desc in columns:
        desc = desc.replace("|", "\\|")[:140]
        lines.append(f"| `{name}` | {dtype} | {desc} |")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nwrote {OUT}")
    print("commit it, then we write catalogs.py against what it actually says")


if __name__ == "__main__":
    main()